"""Word document generator for ITSG-33 reports."""

from typing import Dict, Any, List
from datetime import datetime
from io import BytesIO

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE


class WordReportGenerator:
    """Generate Word documents for ITSG-33 assessments."""

    def __init__(self):
        """Initialize the generator."""
        pass

    def generate_assessment_report(
        self,
        assessment: Dict[str, Any],
        results: Dict[str, Any],
        project_name: str,
        client_id: str,
    ) -> BytesIO:
        """Generate a Word document for the assessment report."""
        doc = Document()

        # Set up styles
        self._setup_styles(doc)

        # Title
        title = doc.add_heading("ITSG-33 Security Assessment Report", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Executive Summary section
        doc.add_heading("Executive Summary", level=1)

        # Summary table
        table = doc.add_table(rows=6, cols=2)
        table.style = "Table Grid"

        rows_data = [
            ("Assessment ID", assessment.get("assessment_id", "N/A")),
            ("Project Name", project_name),
            ("Client", client_id),
            ("Status", assessment.get("status", "Unknown")),
            ("Report Date", datetime.now().strftime("%B %d, %Y")),
            ("Documents Reviewed", f"{assessment.get('document_count', 0)} documents, {assessment.get('diagram_count', 0)} diagrams"),
        ]

        for i, (label, value) in enumerate(rows_data):
            row = table.rows[i]
            row.cells[0].text = label
            row.cells[1].text = str(value)
            # Bold the label
            row.cells[0].paragraphs[0].runs[0].bold = True

        doc.add_paragraph()

        if results:
            self._add_results_section(doc, results)

        # Add ITSG-33 info
        self._add_itsg33_info(doc)

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("Generated by ITSG-33 Accreditation System")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].italic = True

        # Save to BytesIO
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer

    def generate_poam(
        self,
        assessment: Dict[str, Any],
        results: Dict[str, Any],
        project_name: str,
        client_id: str,
    ) -> BytesIO:
        """Generate a Plan of Action and Milestones (POAM) document."""
        doc = Document()

        # Title
        title = doc.add_heading("Plan of Action and Milestones (POA&M)", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_heading("System Information", level=1)

        # System info table
        info_table = doc.add_table(rows=4, cols=2)
        info_table.style = "Table Grid"

        info_data = [
            ("System/Project Name", project_name),
            ("Client/Organization", client_id),
            ("Assessment Date", datetime.now().strftime("%B %d, %Y")),
            ("POA&M Generated", datetime.now().strftime("%B %d, %Y")),
        ]

        for i, (label, value) in enumerate(info_data):
            row = info_table.rows[i]
            row.cells[0].text = label
            row.cells[1].text = str(value)
            row.cells[0].paragraphs[0].runs[0].bold = True

        doc.add_paragraph()

        # Get gaps from results
        coverage = results.get("phases", {}).get("coverage", {})
        no_coverage = coverage.get("no_coverage", [])
        partial_coverage = coverage.get("partial_coverage", [])
        recommendations = results.get("phases", {}).get("recommendations", {})

        doc.add_heading("POA&M Summary", level=1)

        summary = doc.add_paragraph()
        summary.add_run(f"Total Weaknesses Identified: ").bold = True
        summary.add_run(f"{len(no_coverage) + len(partial_coverage)}\n")
        summary.add_run(f"High Priority Items: ").bold = True
        summary.add_run(f"{len(recommendations.get('high_priority', []))}\n")
        summary.add_run(f"Medium Priority Items: ").bold = True
        summary.add_run(f"{len(recommendations.get('medium_priority', []))}\n")

        doc.add_paragraph()

        # POA&M Table
        doc.add_heading("Detailed POA&M Items", level=1)

        if no_coverage or partial_coverage:
            # Create POA&M table
            poam_table = doc.add_table(rows=1, cols=7)
            poam_table.style = "Table Grid"

            # Header row
            header_cells = poam_table.rows[0].cells
            headers = ["ID", "Control", "Weakness", "Remediation", "Resources", "Target Date", "Status"]
            for i, header in enumerate(headers):
                header_cells[i].text = header
                header_cells[i].paragraphs[0].runs[0].bold = True

            # Add high priority items
            item_id = 1
            for item in recommendations.get("high_priority", []):
                row = poam_table.add_row().cells
                row[0].text = f"POAM-{item_id:03d}"
                row[1].text = item.get("control_id", "")
                row[2].text = f"Missing evidence for {item.get('control_name', item.get('control_id', ''))}"
                row[3].text = item.get("action", "Provide required documentation")
                row[4].text = "TBD"
                row[5].text = self._get_target_date(30)  # 30 days for high priority
                row[6].text = "Open"
                item_id += 1

            # Add medium priority items
            for item in recommendations.get("medium_priority", []):
                row = poam_table.add_row().cells
                row[0].text = f"POAM-{item_id:03d}"
                row[1].text = item.get("control_id", "")
                row[2].text = f"Missing evidence for {item.get('control_name', item.get('control_id', ''))}"
                row[3].text = item.get("action", "Provide required documentation")
                row[4].text = "TBD"
                row[5].text = self._get_target_date(60)  # 60 days for medium priority
                row[6].text = "Open"
                item_id += 1

            # Add remaining items from no_coverage (up to 50)
            remaining = [c for c in no_coverage if c.get("control_id") not in
                        [r.get("control_id") for r in recommendations.get("high_priority", [])] +
                        [r.get("control_id") for r in recommendations.get("medium_priority", [])]]

            for ctrl in remaining[:50]:
                row = poam_table.add_row().cells
                row[0].text = f"POAM-{item_id:03d}"
                row[1].text = ctrl.get("control_id", "")
                row[2].text = f"No evidence provided for {ctrl.get('control_name', '')}"
                row[3].text = "Provide policy, procedure, or configuration documentation"
                row[4].text = "TBD"
                row[5].text = self._get_target_date(90)  # 90 days for low priority
                row[6].text = "Open"
                item_id += 1

        else:
            doc.add_paragraph("No weaknesses identified. All controls have sufficient evidence.")

        doc.add_paragraph()

        # Milestones section
        doc.add_heading("Milestones", level=1)

        milestones_table = doc.add_table(rows=1, cols=4)
        milestones_table.style = "Table Grid"

        m_headers = ["Milestone", "Description", "Target Date", "Status"]
        m_header_cells = milestones_table.rows[0].cells
        for i, header in enumerate(m_headers):
            m_header_cells[i].text = header
            m_header_cells[i].paragraphs[0].runs[0].bold = True

        milestones = [
            ("M1", "Address High Priority Controls", self._get_target_date(30), "Not Started"),
            ("M2", "Address Medium Priority Controls", self._get_target_date(60), "Not Started"),
            ("M3", "Address Remaining Controls", self._get_target_date(90), "Not Started"),
            ("M4", "Reassessment", self._get_target_date(120), "Not Started"),
        ]

        for ms in milestones:
            row = milestones_table.add_row().cells
            for i, val in enumerate(ms):
                row[i].text = val

        doc.add_paragraph()

        # Approval section
        doc.add_heading("Approvals", level=1)

        approval_table = doc.add_table(rows=3, cols=3)
        approval_table.style = "Table Grid"

        approval_headers = ["Role", "Name", "Signature/Date"]
        for i, header in enumerate(approval_headers):
            approval_table.rows[0].cells[i].text = header
            approval_table.rows[0].cells[i].paragraphs[0].runs[0].bold = True

        roles = ["System Owner", "ISSO", "Authorizing Official"]
        for i, role in enumerate(roles):
            approval_table.rows[i + 1 if i < 2 else i].cells[0].text = role

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("Generated by ITSG-33 Accreditation System")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].italic = True

        # Save to BytesIO
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer

    def _setup_styles(self, doc: Document):
        """Set up document styles."""
        # Modify existing styles
        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(11)

    def _add_results_section(self, doc: Document, results: Dict[str, Any]):
        """Add results sections to the document."""
        # Summary
        if results.get("summary"):
            s = results["summary"]
            doc.add_heading("Assessment Summary", level=1)

            summary_table = doc.add_table(rows=6, cols=2)
            summary_table.style = "Table Grid"

            summary_data = [
                ("Security Profile", f"Profile {s.get('profile', 2)}"),
                ("Total Controls Required", str(s.get("total_controls", 0))),
                ("Controls with Full Evidence", str(s.get("controls_with_evidence", 0))),
                ("Controls with Partial Evidence", str(s.get("controls_partial", 0))),
                ("Controls Missing Evidence", str(s.get("controls_missing", 0))),
                ("Coverage Percentage", f"{s.get('coverage_percentage', 0)}%"),
            ]

            for i, (label, value) in enumerate(summary_data):
                row = summary_table.rows[i]
                row.cells[0].text = label
                row.cells[1].text = value
                row.cells[0].paragraphs[0].runs[0].bold = True

            doc.add_paragraph()

        # System Analysis
        if results.get("phases", {}).get("system_analysis"):
            sa = results["phases"]["system_analysis"]
            doc.add_heading("System Analysis", level=1)

            analysis_table = doc.add_table(rows=6, cols=2)
            analysis_table.style = "Table Grid"

            analysis_data = [
                ("System Type", sa.get("system_type", "Unknown")),
                ("Data Classification", sa.get("data_classification", "Unknown")),
                ("Confidentiality", sa.get("confidentiality", "Unknown")),
                ("Integrity", sa.get("integrity", "Unknown")),
                ("Availability", sa.get("availability", "Unknown")),
                ("Recommended Profile", f"Profile {sa.get('recommended_profile', 2)}"),
            ]

            for i, (label, value) in enumerate(analysis_data):
                row = analysis_table.rows[i]
                row.cells[0].text = label
                row.cells[1].text = value
                row.cells[0].paragraphs[0].runs[0].bold = True

            doc.add_paragraph()
            doc.add_heading("Rationale", level=2)
            doc.add_paragraph(sa.get("rationale", "No rationale provided."))

        # Coverage
        if results.get("phases", {}).get("coverage"):
            cov = results["phases"]["coverage"]

            # Full coverage
            if cov.get("full_coverage"):
                doc.add_heading("Controls with Full Evidence", level=1)
                self._add_controls_table(doc, cov["full_coverage"][:30])

            # Missing coverage
            if cov.get("no_coverage"):
                doc.add_heading("Controls Missing Evidence", level=1)
                doc.add_paragraph(f"{len(cov['no_coverage'])} controls require evidence documentation:")
                self._add_controls_table(doc, cov["no_coverage"][:30])

        # Recommendations
        if results.get("phases", {}).get("recommendations"):
            rec = results["phases"]["recommendations"]
            doc.add_heading("Recommendations", level=1)

            if rec.get("high_priority"):
                doc.add_heading("High Priority", level=2)
                for item in rec["high_priority"]:
                    p = doc.add_paragraph(style="List Bullet")
                    p.add_run(f"{item.get('control_id', '')}: ").bold = True
                    p.add_run(item.get("action", ""))
                    if item.get("suggested_evidence"):
                        p.add_run(f" ({item['suggested_evidence']})")

            if rec.get("next_steps"):
                doc.add_heading("Next Steps", level=2)
                for step in rec["next_steps"]:
                    doc.add_paragraph(step, style="List Bullet")

    def _add_controls_table(self, doc: Document, controls: List[Dict]):
        """Add a controls table."""
        if not controls:
            return

        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"

        headers = ["Control ID", "Control Name", "Family"]
        for i, header in enumerate(headers):
            table.rows[0].cells[i].text = header
            table.rows[0].cells[i].paragraphs[0].runs[0].bold = True

        for ctrl in controls:
            row = table.add_row().cells
            row[0].text = ctrl.get("control_id", "")
            row[1].text = ctrl.get("control_name", "")
            row[2].text = ctrl.get("family", "")

        doc.add_paragraph()

    def _add_itsg33_info(self, doc: Document):
        """Add ITSG-33 information section."""
        doc.add_heading("About ITSG-33", level=1)
        doc.add_paragraph(
            "ITSG-33 (IT Security Risk Management: A Lifecycle Approach) is the "
            "Government of Canada's framework for managing IT security risks. "
            "It defines security controls across 17 families:"
        )

        families = [
            ("AC", "Access Control"),
            ("AT", "Awareness and Training"),
            ("AU", "Audit and Accountability"),
            ("CA", "Assessment, Authorization, and Monitoring"),
            ("CM", "Configuration Management"),
            ("CP", "Contingency Planning"),
            ("IA", "Identification and Authentication"),
            ("IR", "Incident Response"),
            ("MA", "Maintenance"),
            ("MP", "Media Protection"),
            ("PE", "Physical and Environmental Protection"),
            ("PL", "Planning"),
            ("PS", "Personnel Security"),
            ("RA", "Risk Assessment"),
            ("SA", "System and Services Acquisition"),
            ("SC", "System and Communications Protection"),
            ("SI", "System and Information Integrity"),
        ]

        for code, name in families:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f"{code}").bold = True
            p.add_run(f" - {name}")

    def _get_target_date(self, days: int) -> str:
        """Get target date from now."""
        from datetime import timedelta
        target = datetime.now() + timedelta(days=days)
        return target.strftime("%B %d, %Y")
